include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Security & Best Practices
    - avoid_print
    - avoid_web_libraries_in_flutter
    - no_leading_underscores_for_local_identifiers
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    
    # Code Quality
    - always_declare_return_types
    - avoid_empty_else
    - avoid_returning_null_for_future
    - prefer_single_quotes
    - sort_pub_dependencies
    
    # Documentation
    - public_member_api_docs

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

